;;;; jni-array.import.scm - GENERATED BY CHICKEN 4.8.0.3 -*- Scheme -*-

(eval '(import chicken scheme jni2-lolevel))
(##sys#register-compiled-module
  'jni-array
  (list)
  '((list->array . jni-array#list->array)
    (array->list . jni-array#array->list)
    (array-filter . jni-array#array-filter)
    (array-find . jni-array#array-find)
    (array-map . jni-array#array-map)
    (array-fold . jni-array#array-fold))
  (list)
  (list))

;; END OF FILE
