#>
#include <jni.h>
<#

(module jni-reflection
*
(import chicken scheme foreign)
(import-for-syntax chicken data-structures)
(use srfi-1 lolevel jni matchable)


;; need to handle exception in the jni egg ... till then...
(define (unhandled-exception)
  (exception-describe)
  (error "Native Chicken[jni-reflection]" "-- ): unhandled excpetion in chicken thread :( --"))
(define call-object-method
  (let ((call-object-method* call-object-method))
    (lambda (object method args)
      (let ((result (call-object-method* object method args)))
	(if (exception-check) (unhandled-exception) result)))))


(define (primitive? Class/instance)
  (let* ((Class.isPrimitive/method (method java.lang.Class boolean isPrimitive))
	 (is-primitive             (call-boolean-method Class/instance Class.isPrimitive/method #f)))
    is-primitive))



(define (reflected-field object field-name)
  (let* ((object-class (get-object-class object))
	 (Class.getDeclaredField/method (method java.lang.Class java.lang.reflect.Field getDeclaredField java.lang.String))
	 (field-name (jstring (symbol->string field-name)))
	 (args (make-jvalue-array 1))
	 (Field/instance (call-object-method object-class Class.getDeclaredField/method
					     (begin
					       (set-object-jvalue! args 0 field-name) args))))
    (delete-local-ref field-name)
    (delete-local-ref object-class)
    (free-jvalue-array args)
    Field/instance))

(define (reflected-field-modifiers Field/instance)
  (let* ((Field.getModifiers/method (method java.lang.reflect.Field int getModifiers))
	 (modifiers                 (call-int-method Field/instance Field.getModifiers/method #f)))
    modifiers))
(define (reflected-field-type Field/instance)
  (let* ((Field.getType/method (method java.lang.reflect.Field java.lang.Class getType))
	 (Class/instance       (call-object-method Field/instance Field.getType/method #f)))
    Class/instance))


(define (field object field-name)
  (let* ((Field/instance       (reflected-field object    field-name))
	 (Field.type/Class     (reflected-field-type      Field/instance))
	 (Field.modifiers/int  (reflected-field-modifiers Field/instance)))

    (let ((return-value
	   (if (primitive? Field.type/Class)
	       (case (string->symbol (to-string Field.type/Class))
		 ((byte)
		  (if (static? Field.modifiers/int)
		      (get-static-byte-field    object (Field->field-id Field/instance))
		      (get-byte-field           object (Field->field-id Field/instance))))
		 ((short)
		  (if (static? Field.modifiers/int)
		      (get-static-short-field   object (Field->field-id Field/instance))
		      (get-short-field          object (Field->field-id Field/instance))))
		 ((int)
		  (if (static? Field.modifiers/int)
		      (get-static-int-field     object (Field->field-id Field/instance))
		      (get-int-field            object (Field->field-id Field/instance))))
		 ((long)
		  (if (static? Field.modifiers/int)
		      (get-static-long-field    object (Field->field-id Field/instance))
		      (get-long-field           object (Field->field-id Field/instance))))
		 ((float)
		  (if (static? Field.modifiers/int)
		      (get-static-float-field   object (Field->field-id Field/instance))
		      (get-float-field          object (Field->field-id Field/instance))))
		 ((double)
		  (if (static? Field.modifiers/int)
		      (get-static-double-field  object (Field->field-id Field/instance))
		      (get-double-field         object (Field->field-id Field/instance))))
		 ((char)
		  (if (static? Field.modifiers/int)
		      (get-static-char-field    object (Field->field-id Field/instance))
		      (get-char-field           object (Field->field-id Field/instance))))
		 ((boolean)
		  (if (static? Field.modifiers/int)
		      (get-static-boolean-field object (Field->field-id Field/instance))
		      (get-boolean-field        object (Field->field-id Field/instance))))
		 (else
		  (print (format "): -- Field has unkown primitive type ~A -- :(" (to-string Field.type/Class)))(exit -1)))
	       (let ((return-value
		      (if (static? Field.modifiers/int)
			  (get-static-object-field     object (Field->field-id Field/instance))
			  (get-object-field            object (Field->field-id Field/instance)))))
		 (if return-value (set-finalizer! return-value delete-local-ref) return-value)))))
      (delete-local-ref Field/instance)
      (delete-local-ref Field.type/Class)

      (if (exception-check) (unhandled-exception) return-value))))

(define (set-field! object field-name value)
  (let* ((Field/instance       (reflected-field object    field-name))
	 (Field.type/Class     (reflected-field-type      Field/instance))
	 (Field.modifiers/int  (reflected-field-modifiers Field/instance)))

    (let ((return-value
	   (if (primitive? Field.type/Class)
	       (case (string->symbol (to-string Field.type/Class))
		 ((byte)
		  (if (static? Field.modifiers/int)
		      (set-static-byte-field    object (Field->field-id Field/instance) value)
		      (set-byte-field           object (Field->field-id Field/instance) value)))
		 ((short)
		  (if (static? Field.modifiers/int)
		      (set-static-short-field   object (Field->field-id Field/instance) value)
		      (set-short-field          object (Field->field-id Field/instance) value) ))
		 ((int)
		  (if (static? Field.modifiers/int)
		      (set-static-int-field     object (Field->field-id Field/instance) value)
		      (set-int-field            object (Field->field-id Field/instance) value)))
		 ((long)
		  (if (static? Field.modifiers/int)
		      (set-static-long-field    object (Field->field-id Field/instance) value)
		      (set-long-field           object (Field->field-id Field/instance) value)))
		 ((float)
		  (if (static? Field.modifiers/int)
		      (set-static-float-field   object (Field->field-id Field/instance) value)
		      (set-float-field          object (Field->field-id Field/instance) value)))
		 ((double)
		  (if (static? Field.modifiers/int)
		      (set-static-double-field  object (Field->field-id Field/instance) value)
		      (set-double-field         object (Field->field-id Field/instance) value)))
		 ((char)
		  (if (static? Field.modifiers/int)
		      (set-static-char-field    object (Field->field-id Field/instance) value)
		      (set-char-field           object (Field->field-id Field/instance) value)))
		 ((boolean)
		  (if (static? Field.modifiers/int)
		      (set-static-boolean-field object (Field->field-id Field/instance) value)
		      (set-boolean-field        object (Field->field-id Field/instance) value)))
		 (else
		  (print (format "): -- Field has unkown primitive type ~A -- :(" (to-string Field.type/Class)))(exit -1)))
	       (if (static? Field.modifiers/int)
		   (set-static-object-field     object (Field->field-id Field/instance) value)
		   (set-object-field            object (Field->field-id Field/instance) value)))))
      (delete-local-ref Field/instance)
      (delete-local-ref Field.type/Class)
      
      (if (exception-check) (unhandled-exception) return-value))))





(define (methods Class/instance)
  (let* ((Class.getMethods/method (method java.lang.Class #(java.lang.reflect.Method) getMethods))
	 (methods-array           (call-object-method Class/instance Class.getMethods/method #f))
	 (methods-list            (array->list methods-array)))
    (delete-local-ref methods-array)
    methods-list))
(define (declared-methods Class/instance)
  (let* ((Class.getDeclaredMethods/method (method java.lang.Class #(java.lang.reflect.Method) getDeclaredMethods))       
	 (methods-array                   (call-object-method Class/instance Class.getDeclaredMethods/method #f))
	 (methods-list                    (array->list methods-array)))
    (delete-local-ref methods-array)
    methods-list))
(define (method-name Method/instance)
  (let* ((Method.getName/method (method java.lang.reflect.Method java.lang.String getName))
	 (String/instance       (call-object-method Method/instance Method.getName/method #f)))
    String/instance))
(define (method-return-type Method/instance)
  (let* ((Method.getReturnType/method (method java.lang.reflect.Method java.lang.Class getReturnType))
	 (Class/instance              (call-object-method Method/instance Method.getReturnType/method #f)))
    Class/instance))
(define (method-parameters Method/instance)
  (let* ((Method.getParameterTypes/method (method java.lang.reflect.Method #(java.lang.Class) getParameterTypes))
	 (class-object-array (call-object-method Method/instance Method.getParameterTypes/method #f))
	 (class-object-list  (array->list class-object-array)))
    (delete-local-ref class-object-array)
    class-object-list))
(define (method-modifiers Method/instance)
  (let* ((Method.getModifiers/method (method java.lang.reflect.Method int getModifiers))
	 (modifiers                  (call-int-method Method/instance Method.getModifiers/method #f)))
    modifiers))

(define (methods-by-name object name)
  (let* ((all-methods (methods object))
	 (same-name (filter (lambda (method)
			      (if (equal? (symbol->string name) 
					  (let* ((name* (method-name method))
						 (name  (jstring->string name*)))
					    (delete-local-ref name*) name))
				  #t (begin
				       (delete-local-ref method) #f)))
			    all-methods)))
    same-name))

(define (print-methods object)
  (let* ((own-methods (methods object))
	 (all-methods (declared-methods object)))

    (print "-- all")
    (for-each jprint all-methods)
    (for-each delete-local-ref all-methods)
    
    (print "-- declared")
    (for-each jprint own-methods)
    (for-each delete-local-ref own-methods)))


(define (method-resolve object name args)
  (let ((m (methods-by-name object name)))
    (if (null? m)
	(error "resolve method" (format "method not found: ~A with ~A on ~A" name args (to-string object))))
    (if (null? args)
	(car m)
	(find
	 (lambda (method)
	   (jprint method)
	   (let ((method-args (method-parameters method)))
	     (for-each delete-local-ref method-args)
	     (= (length args)
		(length method-args)))) m))))

(define (make-jvalue-args args class-objects)
  (if (null? args)
      #f
      (let ((jvalue-array (make-jvalue-array (length args))))
	(fold (lambda (arg i)
		(let ((type (list-ref class-objects i)))
		  (if (pointer? arg)
		      (set-object-jvalue! jvalue-array i arg)
		      (case (string->symbol (to-string type))
			((boolean)
			 (set-boolean-jvalue! jvalue-array i arg))
			((char)
			 (set-char-jvalue! jvalue-array i arg))
			((byte)
			 (set-byte-jvalue! jvalue-array i arg))
			((short)
			 (set-short-jvalue! jvalue-array i arg))
			((int)
			 (set-int-jvalue! jvalue-array i arg))
			((long)
			 (set-long-jvalue! jvalue-array i arg))
			((float)
			 (set-float-jvalue! jvalue-array i arg))
			((double)
			 (set-double-jvalue! jvalue-array i arg))
			(else
			 (error "fooooooo" "baaaaaaar!!!!")))))
		(+ i 1))
	      0
	      args)
	jvalue-array)))

(define (call object name . args*)
  (let* ((object-class            (get-object-class object))
	 (Method/instance         (method-resolve object-class name args*))
	 (Method.modifiers/int    (method-modifiers Method/instance))
	 (Method.returnType/Class (method-return-type Method/instance))
	 (arg-classes             (method-parameters Method/instance))
	 (method (Method->method-id Method/instance))
	 (args (make-jvalue-args args* arg-classes)))
    (for-each delete-local-ref arg-classes)

    (print (format "found: ~A" (to-string Method/instance)))
    (print (format "calling ~A with ~A on ~A\n-------" name args* (to-string object-class)))

    (let ((return-value
	   (if (primitive? Method.returnType/Class)
	       (case (string->symbol (to-string Method.returnType/Class))
		 ((void)
		  (if (static? Method.modifiers/int)
		      (call-static-void-method object-class method args)
		      (call-void-method object method args)))
		 ((byte)
		  (if (static? Method.modifiers/int)
		      (call-static-byte-method object-class method args)
		      (call-byte-method object method args)))
		 ((short)
		  (if (static? Method.modifiers/int)
		      (call-static-short-method object-class method args)
		      (call-short-method object method args)))
		 ((int)
		  (if (static? Method.modifiers/int)
		      (call-static-int-method object-class method args)
		      (call-int-method object method args)))
		 ((long)
		  (if (static? Method.modifiers/int)
		      (call-static-long-method object-class method args)
		      (call-long-method object method args)))
		 ((float)
		  (if (static? Method.modifiers/int)
		      (call-static-float-method object-class method args)
		      (call-float-method object method args)))
		 ((double)
		  (if (static? Method.modifiers/int)
		      (call-static-double-method object-class method args)
		      (call-double-method object method args)))
		 ((char)
		  (if (static? Method.modifiers/int)
		      (call-static-char-method object-class method args)
		      (call-char-method object method args)))
		 ((boolean)
		  (if (static? Method.modifiers/int)
		      (call-static-boolean-method object-class method args)
		      (call-boolean-method object method args)))
		 (else
		  (print (format "): -- Method has unkown primitive return type ~A -- :(" (to-string Method.returnType/Class)))(exit -1)))
	       (let ((return-value
		      (if (static? Method.modifiers/int)
			  (call-static-object-method object-class method args)
			  (call-object-method object method args))))
		 (if return-value (set-finalizer! return-value delete-local-ref) return-value)))))

      (delete-local-ref object-class)
      (delete-local-ref Method/instance)
      (delete-local-ref Method.returnType/Class)
      (free-jvalue-array args)

      (if (exception-check) (unhandled-exception) return-value))))

)
